"""Update post_image

Revision ID: 93f7eb31304e
Revises: dd616eebd846
Create Date: 2025-10-22 14:40:59.454425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f7eb31304e'
down_revision: Union[str, Sequence[str], None] = 'dd616eebd846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_images', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('post_images_post_id_fkey'), 'post_images', type_='foreignkey')
    op.create_foreign_key(None, 'post_images', 'posts', ['post_id'], ['post_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_images', type_='foreignkey')
    op.create_foreign_key(op.f('post_images_post_id_fkey'), 'post_images', 'posts', ['post_id'], ['post_id'])
    op.alter_column('post_images', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
